### ISSUE TITLE
Choosing a channel

### ISSUE THREAD

**Issue by van-sprundel** [yobson1/webfishing-midi#1]
Hey, love the tool!

Do you know if it would be possible to add a "choose a midi channel" option? 
Some midi's I have include drum channels, and I'd rather just choose the proper melody.

**Comment by yobson1** [comment]
I have something prepared to address this, could you send the midi file you have for me to test it with?

**Comment by van-sprundel** [comment]
[This](https://freemidi.org/download4-13466-game-of-thrones-tv-themes) seems like a good enough example. In a [midi editor](https://signal.vercel.app) you can see it has a piano channel that would only add noise.

**Comment by yobson1** [comment]
I just pushed the changes I've made that include track selection. It looks like a lot of midis just don't include track names/instruments though. Even that one you sent has no track name message in it. In the editor you linked it says they're all "Acoustic Guitar (nylon)" which I'm guessing is just what it defaults to if there is no track name meta message in the file.

**Comment by yobson1** [comment]
Maybe it's not assuming, for [this one](https://api.nanomidi.net/api/midis/Ievan_Polkka_284.mid) the editor shows both tracks as Piano but I'm not sure where it's getting that from

**Comment by yobson1** [comment]
Ok I see that the game of thrones one had instrument name messages but not track name messages. It seems they are used interchangeably depending on the midi.

**Comment by yobson1** [comment]
added in 1.1.0
